packages:
  - 'apps/**'
  - 'packages/*'
allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': false
  esbuild: false
  prisma: false
catalog:
  'typescript': '^6.0.3'
  '@types/node': '^25.8.0'
  'tsx': '^4.22.1'
