#!/usr/bin/env sh
# pnpm ts:check # 检查类型
pnpm tsc:admin # 检查 admin 项目的类型
pnpm tsc:client # 检查 client 项目的类型
pnpm tsc:server # 检查 server 项目的类型
pnpm lint # 检查代码质量 -- 不修复
pnpm fmt # 格式化代码 -- 自动修复
pnpm lint:spellcheck # 检查拼写错误
