#!/usr/bin/env sh
pnpm lint-staged # 检查暂存区代码 含 pnpm fmt # 格式化代码 -- 自动修复
pnpm lint # 检查代码质量 -- 不修复
pnpm lint:spellcheck # 检查拼写错误
pnpm tsc:admin # 检查 admin 项目的类型
pnpm tsc:client # 检查 client 项目的类型
pnpm tsc:server # 检查 server 项目的类型
pnpm tsc:components # 检查 components 项目的类型
pnpm tsc:utils # 检查 utils 项目的类型
pnpm tsc:types # 检查 types 项目的类型